### ISSUE TITLE
[FEATURE] Distinguish items by hue

### ISSUE THREAD

**Issue by Phroster** [markdwags/Razor#101]
Currently the razor scripting cannot distinguish when items have the same graphics ID but a different hue, for instance, leather is seen as the same as dull hide when using agents.

Allow commands that are related to targeting by graphics ID, to distinguish hues.
Allow agents to distinguish items that have the same graphics ID, to distinguish hues.

**Comment by markdwags** [comment]
This was added in https://github.com/markdwags/Razor/releases/tag/v1.7.3.36
