### ISSUE TITLE
[BUG] Screenshots not capturing the screen.

### ISSUE THREAD

**Issue by Alias-Alan** [markdwags/Razor#104]
When using the in-razor "Take ScreenShot Now" or using capture screen-shot on death/my death, these produce the file in the directory but does not follow through the process of copying the captured screen and saving it to the file itself. This has only recently started happening.

**Comment by markdwags** [comment]
I believe this is related to ClassicUO's updated engine (from OpenGL to DirectX) -- it needs more research.

**Comment by markdwags** [comment]
This was fixed with https://github.com/andreakarasho/ClassicUO/commit/b993b2bbc4fd656ee6779e4bfab4f51641c58790
