### ISSUE TITLE
Timer functionality

### ISSUE THREAD

**Issue by thiagotigaz** [markdwags/Razor#105]
Is there any plan to add a timer functionality? I want to be able to develop non blocking macros that check timers before doing action and not rely on fixed pauses/sleep.

**Comment by HankTheDrunk** [comment]
Extremely unlikely as this is a UO:Ren Community Edition, I don't think Telamon/Chris would be okay with that level of automation.
No discredit to quick for all his hard work. It's been expressed they don't want a fully automated macro suite.

**Comment by markdwags** [comment]
This version isn't tied to any specific shard, instead this version of Razor has long been driven by the project's goal which is not to turn Razor into another Steam or Razor Enhanced assistant.

So it doesn't have as much to do with what a specific shard owner wants or doesn't (and nor do I consultant with any shard owners) -- it's more taking the feature request and holding it up to the project's goals and see if it fits.

I've had this request before, even before the scripting engine was added.  Razor has always been a 1 macro at a time assistant and there aren't any plans to change that.
