### ISSUE TITLE
[FEATURE] Clear journal with script

### ISSUE THREAD

**Issue by sp1r17** [markdwags/Razor#108]
Currently it does not appear that the scripting option has a feature to clear the journal, so when checking sys messages, the script will continuously see an already-present sys message and loop over and over.

Looking for a feature to clear the journal before checking for a sys message.

**Comment by markdwags** [comment]
Sure, that makes sense.  Since you can do it with a trick, like you mentioned, a loop to "clear" it out, should be as simple as a command.

**Comment by markdwags** [comment]
Added in https://github.com/markdwags/Razor/commit/67b2ddce7c7f5c49d3664cbc0671e900a0702342
