### ISSUE TITLE
Auto Open Corpses as they come into range

### ISSUE THREAD

**Issue by aclark13** [markdwags/Razor#11]
Change "Auto Open Corpses" to open corpses as you walk up to them.  When playing any kind of ranged character (Tamer, Summoner, Archer, etc) the feature cannot be used after death when you walk up to the corpse.  You have to be within 1-2 tiles for the feature to work.

**Comment by markdwags** [comment]
Feature added to CUO client, not required in an assistant anymore.

https://github.com/andreakarasho/ClassicUO/pull/500
