### ISSUE TITLE
[BUG] Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by eruspravus** [markdwags/Razor#112]
Im using ClassicUO 0.1.4.0 (also tested with 0.1.3.38) and Razor 1.6.5.16.

When i Disable the "Show [Party-Friend] overhead" setting under Friends and im in a party. I get a "Object reference not set to an instance of an object." for every name shown in-game. And if a try do an All-Names macro everything crash.

`System.NullReferenceException: Object reference not set to an instance of an object.
   at Assistant.Core.FriendsManager.ShowOverhead(Mobile mobile)
   at Assistant.PacketHandlers.ClientSingleClick(PacketReader p, PacketHandlerEventArgs args)
   at Assistant.PacketHandler.ProcessViewers(List'1 list, PacketReader p)`

If im not in a party or if i check the setting mentioned above, the error goes away.
![image](https://user-images.githubusercontent.com/5288253/89901286-32882b80-dbe5-11ea-9dc7-25fa4615ebad.png)

**Comment by markdwags** [comment]
Fixed in latest dev preview, workaround is to add your party member as a friend, or leave the checkbox enabled.
