### ISSUE TITLE
[BUG] count not working for kindling

### ISSUE THREAD

**Issue by wsavran** [markdwags/Razor#119]
client: ClassicUO

problem: count does not properly recognize 'kindling' when scripting. this can be reproduced by putting kindling in your back and executing the following script. i noticed that 'kindling' is not an option if this were done through the macro interface, so maybe its just simply a keyword that needs added to the structure that holds the list of items  

id be happy to try and help fix the problem, but i would definitely need some gentle nudging in the right direction.

```
if count 'kindling' > 0
    say 'found some kindling'
endif
```
this can be worked around using findtype, but i think that count provides more granular control over what the script is doing.
```
if findtype 'kindling' true
    say 'found some kindling'
endif
```

**Comment by markdwags** [comment]
You need to have the counter defined in Display/Counters->Counters tab.

Add an entry for kindle and it should pick it up.

**Comment by wsavran** [comment]
Cool thanks for the quick reply! I added kindling using the 'target' option and its giving a "Script error: Object reference not set to an instance of an object" What did I do wrong?
