### ISSUE TITLE
[BUG] Targeting not working in subroutine script

### ISSUE THREAD

**Issue by wsavran** [markdwags/Razor#123]
I'm running on the ClassicUO client.

I'm having an Issue targeting self inside of script that is called from another script.  Inside the called script, I activate a restock agent and then cast a spell on myself. The called script runs properly on its own, but when called from another scripts hangs on the target 'self' line. The client gives me the targeting option but does not actually target 'self'.  The script has no issue targeting the container used for restocking. 

I would expect that the script should have the same behavior whether it is executed through a HotKey or the "play" option in the GUI or called using the `script` command from another script. I have tried using changing arguments for the 'self' including hex and decimal serial.

i have reproduced this issue by creating two scripts 

script 1
name: dispatch_script
contents:
 ```
script 'subroutine_script'
```

script 2
name: subroutine_script
contents: 
```
cast 'invisibility'
waitfortarget 2500
target 'self'
```

if i run 'script 2' it works as expected. if i run 'script 1', it does not properly target self.

**Comment by markdwags** [comment]
Hmm, I'm unable to reproduce this. 

One script is called "test1"

```
overhead 'first'
script 'test2'
```

And the second is "test2"

```
overhead 'second'
cast 'invisibility'
waitfortarget 2500
target 'self'
```

![2020-09-18_00-01-39](https://user-images.githubusercontent.com/577652/93558029-26a92b00-f942-11ea-84eb-6d236bf88a30.gif)

**Comment by wsavran** [comment]
thanks for looking into this. i will close for now, and look into it a bit more. it looks like it might be caused by some issues with the profile. i will reopen a new issue if i find out more
