### ISSUE TITLE
[BUG] "script" command in a loop

### ISSUE THREAD

**Issue by bacca87** [markdwags/Razor#125]
I'm using ClassicUO.

if i use the "script" command, the main script ends after the first call.

Example code:

"say hi" script:

> say 'hi'
> wait 1000

main script:

> script 'say hi'
> loop

instead of looping saying "hi", the script ends at the first "hi"

**Comment by markdwags** [comment]
That looks to be working as expected.  You can only run one script at a time.

If you want the `say hi` script to loop, it needs to be 

```
say 'hi'
wait 1000
loop
```

and your main script then would be 

```
script 'say hi'
```

**Comment by bacca87** [comment]
if someone needs this kind of behaviour in order to make complex script, like i'm trying to do, you can work around this limit just calling back the main script like follow:

Example code:

"say hi" script:

> say 'hi'
> wait 1000
> script 'main'

main script:

> script 'say hi'

It's a little tricky to handle this kind of loop but it's possible. 
I've done a complex mining macro without duplicate 10 times the same code inside a single script that is very annoyng and difficult to mantain.

**Comment by markdwags** [comment]
Yep, that works as well.
