### ISSUE TITLE
Queueing drag and drop does not work with scripts [BUG]

### ISSUE THREAD

**Issue by Kadoba** [markdwags/Razor#138]
Running ClassicUO 0.1.6.0 with Razor 1.6.7.0

Queuing drag and drop requests does not work with scripts and causes the queue to become stuck until it is disabled in the options or the character logs out. A queue message is generated but the drop action never happens.

Example Script:
1. Pick up one mandrake root
2. Drop one mandrake root
3. Pick up one nightshade
4. Drop one nightshade

In the above script the first three actions would happen but the nightshade would not be dropped on action 4. Instead a message of "Macro Warning: Not holding anything." is given. Any further actions will be queued and never executed.

**Comment by markdwags** [comment]
Add a wait between 2 and 3 and see if you still run into the issue.

**Comment by Kadoba** [comment]
Thanks for the reply. This does make the script more stable but the problem can still happen like if the player accidently does an action while the script is running. It wouldn't be so bad if the queue just missed some actions every once in a while but when it freezes up the player cannot interact with any object including containers, consumables, doors, etc.

**Comment by Saralise** [comment]
> Running ClassicUO 0.1.6.0 with Razor 1.6.7.0
> 
> Queuing drag and drop requests does not work with scripts and causes the queue to become stuck until it is disabled in the options or the character logs out. A queue message is generated but the drop action never happens.
> 
> Example Script:
> 
> 1. Pick up one mandrake root
> 2. Drop one mandrake root
> 3. Pick up one nightshade
> 4. Drop one nightshade
> 
> In the above script the first three actions would happen but the nightshade would not be dropped on action 4. Instead a message of "Macro Warning: Not holding anything." is given. Any further actions will be queued and never executed.

Thanks for the info on how to get out of it when it happens.  The 'disable in options'.  I have this problem when something goes wrong.  I have to wait for a long time for it to get unstuck.  When it happens, I usually just make a game out of it and move everything in my pack around to watch it all disappear and see the queue number get bigger.

**Comment by markdwags** [comment]
Sorry for the delay, I believe I identified the issue and fixed it (see gif)

![2021-01-14_17-14-14](https://user-images.githubusercontent.com/577652/104660331-f1141480-568b-11eb-9778-8d0a1e9d33f3.gif)

It also effects `lifttype` and a few others, so addressing those before closing this issue.
