### ISSUE TITLE
[BUG] OSI client freezes during EA server login

### ISSUE THREAD

**Issue by QuentinJones** [markdwags/Razor#145]
Trying to connect to Official EA/Broadsword servers using OSI client. 
**Settings:**
 > Host login.ultimaonline.com
> Port: 2593
> Patch encryption: Tried both doesn't matter

The client launches fine but when clicking login the game just shows "Connecting..." and locks up for a long time and then eventually "Couldn't connect to Ultima Online...". 

I'm able to connect to another server, so I don't think it's just a setup issue unless there is something specific for EA servers.  When I enabled packet logging it looks like a login packet never even gets sent to the server. Tried debugging a bit and as far as I can tell everything goes fine inside `InstallLibrary`, but `WndPrc` never seems to get any message triggering the `UONetMessage.Connect` case in `OSI.OnMessage`. I suppose something might be going wrong in crypt.cpp, but I'm not really sure where to look.

**Comment by markdwags** [comment]
Just to note, we don't provide any official support for the OSI servers as they have a strict no 3rd party programs policy and we don't want to be seen as encouraging users to break a ToS they agreed to willingly.

**Comment by QuentinJones** [comment]
Seems to have been a configuration issue. I changed the port to 7776 and it's working now.
