### ISSUE TITLE
Ability to COUNT without setting a COUNTER

### ISSUE THREAD

**Issue by gauchotche** [markdwags/Razor#146]
This is my suggestion...

if count '3132' > 10
XXXXX
endif

so it would count directly by the object ID... that would make it much more straightforwarded...

thanks!

**Comment by gauchotche** [comment]
I would like very much to see this implemented in next version please

**Comment by gauchotche** [comment]
another idea would be using the 'findtype' function... like:

if findtype 'garlic' ('3434') > 10
XXXXXX
endif

**Comment by gauchotche** [comment]
by using findtype you may prevent conflicts of already defined COUNTERS with the same name... so count/counters would use COUNTERS defined in that specific tab... while findtype would only use in-game names/ids, like 'garlic' or '3434'

**Comment by alikrc** [comment]
+1 on this. Mark if you can show direction i can also check the source code if i can implement it

**Comment by markdwags** [comment]
For now, I'm going to keep the existing Razor counting system vs. having to build another system that counts on the fly.
