### ISSUE TITLE
Timeout parameter missing for 'waitforgump' script command

### ISSUE THREAD

**Issue by dissident76** [markdwags/Razor#147]
Please add a timeout parameter to waitforgump, waitforprompt, waitformenu, just like you did with waitforsysmsg.
The macro command "Wait For Gump" also has a timeout, so the script version not having a timeout parameter makes it difficult to migrate some macros to scripts.

Thank you!

**Comment by dissident76** [comment]
waiforgump fails to wait at all when [timeout] parameter passed, if there is a previously opened gump.
This script will not run as expected, when run repeteadly without closing the [profile gump

say '[profile'
waitforgump 2976808305 2000

#2976808305 is the gump id for "tracking skill". Script should stop at least 2 secs, since the id gump is not on the screen. But there is a previous gump ([profile), so it skips the wait.

problem does not arise when using waitforgump without [timeout] parameter, or when there is no other gump on the screen ([profile gump closed)

**Comment by markdwags** [comment]
I see the issue, pushed a fix, it should be building now.  Let me know if that clears it up. Thanks!

**Comment by dissident76** [comment]
Seems fixed, thanks!
