### ISSUE TITLE
Ability to lift by counter name [FEATURE]

### ISSUE THREAD

**Issue by gauchotche** [markdwags/Razor#148]
Suggestion:

if count 'Item Tinker' > 0
    **lifttype 'Item Tinker'**
    droprelloc 0 0
endif

**Comment by markdwags** [comment]
If you have a counter for "Item Tinker" -- you already know what the item is, so you can simply do `lifttype 'name of item'`  to accomplish what you're doing.

**Comment by gauchotche** [comment]
it's hard to know the exact and correct item names, so when you set a counter you create an alias, which would make it much easier to use in the lifttype command

**Comment by markdwags** [comment]
> it's hard to know the exact and correct item names, so when you set a counter you create an alias, which would make it much easier to use in the lifttype command

It's very easy to use the `>info` command to get that info, not sure what's hard about that.

**Comment by gauchotche** [comment]
Well, it's quality of life improvements, if i can directly lift by my
counter name, it's easier. Small improvements that don't alter the gameplay
but makes stuff easier. Is course those qol might be hard to code, making
it a burden to you. But if it's easy i don't see a reason to not make it.
