### ISSUE TITLE
[BUG] Auto-open doors in CUO don't open on direction change

### ISSUE THREAD

**Issue by markdwags** [markdwags/Razor#15]
**Please include if you are using the standard OSI client or using ClassicUO.**
CUO Only

Remember, **Great Bug Reports** tend to have:

- A quick summary and/or background of the issue

When you are standing on a single tile, and move to face a door, the door doesn't open with Automatically Open Doors enabled.  In the standard OSI client it does.

- What you expected would happen

Turning should open the door even if you don't move.  Moving into the door correctly opens it.

- What actually happens

The door doesn't open, but if you debug the code, you do see the OpenDoorMacro packet sent.

**Comment by DarkLotus** [comment]
It's being triggered twice so it opens and then closes before you see anything, walking has the same issue on linux,  Ive quick fixed it locally by adding a Timer to autoopen doors, only allowing it to fire once every second though theres a deeper issue causing things to trigger twice.

**Comment by markdwags** [comment]
On Windows, I see it firing once regardless if I change direction into it, or I walk towards it.

I can trace both, turning or walking into, and both call OpenDoorMacro once. However, the direction turn, even though it calls it, the door doesn't open.

If I add a 10ms delay before I use OpenDoor on a direction turn, it works.

**Comment by markdwags** [comment]
Fixed with above commit
