### ISSUE TITLE
Consider implementing a "find" script expression for specific objects [FEATURE]

### ISSUE THREAD

**Issue by Kadoba** [markdwags/Razor#150]
The expressions findbuff and findtype are both implemented but there doesn't seem to be one to check for the existence of a specific known item or entity. Having such an expression named "find" would be consistent with the naming scheme for lift and lifttype.

As for an example, let's say you have a reagent bag with an organizer assigned to it. Obviously you can easily lose this. You could use a macro to trigger the organizer but if the bag can't be found the script requests you assign a new one first. 

```
// Fires organizer 4. If it can't be found then it asks the player to assign a new one.
if not find 'regbag'
   setvar 'regbag'
   organizer 4 'set'
   waitfortarget
   target 'regbag'
endif
organizer 4
```

**Comment by markdwags** [comment]
Just to clarify, `find` would be doing a check if your variable (in this case `regbag`) could be found?

**Comment by Kadoba** [comment]
Yes or any serial

**Comment by markdwags** [comment]
Closing this request for now. If it gains more interest we can look at it again.
