### ISSUE TITLE
targettype RANGE not working [BUG]

### ISSUE THREAD

**Issue by gauchotche** [markdwags/Razor#152]
The targettype RANGE option, if set true, will not consider backpack.

I also suggest the BACKPACK option to be added to findtype

**Comment by markdwags** [comment]
This was already fixed in https://github.com/markdwags/Razor/commit/84cc4a38afff92a8393e53d7ee7d73b08513520c and findtype does support backpack.

**Comment by gauchotche** [comment]
thanks
