### ISSUE TITLE
[BUG] Razor can't open Data Directory. 

### ISSUE THREAD

**Issue by burakt91** [markdwags/Razor#159]
Using with ClassicUO client on Windows 10 20H2.

Razor says **Access Denied** when i click **Advanced > Open Data Directory** button.
Also, when i press **Macros > right click a macro > Open Externally** Razor says **Unable to open macro file**.

So i can't find where my macro text files stored on my computer. I checked many possible locations but didn't find them.

**Comment by markdwags** [comment]
They're in the same location as Razor.exe but sounds like you might have permission issues.

**Comment by burakt91** [comment]
OK. I think i understand now. I'm playing on UO Outlands shard. So, i'm using their launcher. I found my macro files in this path: **C:\Program Files (x86)\Ultima Online Outlands\ClassicUO\Data\Plugins\Assistant\Macros**. And i didn't find any Razor.exe file. I think they embedded razor into their launcher or ClassicUO client. (I only used their setup file, then UO and Razor came along with it.) So maybe my permission issue is not causing from this Razor standalone project. Because i think i've no standalone Razor installation.

**Comment by markdwags** [comment]
Thanks for the update. Yes, they embed this version of Razor into ClassicUO, so it might be related to that and because its in that folder which usually has additional permissions. I'd recommend reaching out to their support.  Good luck!
