### ISSUE TITLE
Typing Issues

### ISSUE THREAD

**Issue by ichiokada** [markdwags/Razor#16]
- can't type in login screen
- can't type when "always on top" is enabled
- after awhile of typing in game, typing start to have missing strokes( delay) ? so it become difficult to type
-  Error   | Profiler.ExitProfiledContext: context_name does not match current context. 

on ClassicUO dev 0.0.1.223  
Outlands Shard
Razor ver v1.6.0.6

**Comment by markdwags** [comment]
Known issue, related to DoEvents and CUO's TextInput. Leaving open until fixed.

**Comment by markdwags** [comment]
This was resolved with PR https://github.com/markdwags/Razor/pull/22
