### ISSUE TITLE
[BUG] weather and season razor commands in game giving exceptions

### ISSUE THREAD

**Issue by alikrc** [markdwags/Razor#161]
![image](https://user-images.githubusercontent.com/2185905/114277473-018e1e00-9a34-11eb-9d87-43b1ae1b7a35.png)

ClassicUO,
Repro steps:
use weather command in game:
">weather"
![image](https://user-images.githubusercontent.com/2185905/114277590-72353a80-9a34-11eb-91ae-2e3b5d0b9dd8.png)

**Comment by markdwags** [comment]
That's more of a debug command that doesn't have param count checks. Please use the correct params for the command and it should be fine.

http://www.razorce.com/faq/#in-game-commands
