### ISSUE TITLE
[FEATURE] Pet / target HP

### ISSUE THREAD

**Issue by mikensan** [markdwags/Razor#166]
All feature requests will be considered, but not all will be implemented but please don't let that discourage you from submitting more.

**Is your feature request related to a problem? Please describe.**
No problem. Trying to heal pets / targets based on their HP instead of a timer.

**Describe the solution you'd like**
Ability to use hp/hits against a target or varabile IE: if hits 'pet1' < 200

**Describe alternatives you've considered**
None

**Additional context**
Also a similar function from steam would be nice "diffhits".

**Comment by markdwags** [comment]
Thanks for the suggestion. Right now, I don't have any plans to enable Razor to track the health of other mobiles (such as pets or other people in pvp).  I'll reference this feature request if that ever changes.
