### ISSUE TITLE
[FEATURE] Razor scripting engine expression to detect combat mode

### ISSUE THREAD

**Issue by comiluv** [markdwags/Razor#169]
All feature requests will be considered, but not all will be implemented but please don't let that discourage you from submitting more.

**Is your feature request related to a problem? Please describe.**
Scripting can be improved if the program can detect the player's combat mode.

**Describe the solution you'd like**
For example the player would write a script,
```
target next nonfriendly
if combatmode
  attack lasttarget
endif
```
This would make the script to attack when the player chooses to, and not if the player doesn't want that

**Describe alternatives you've considered**

**Additional context**

**Comment by markdwags** [comment]
`warmode` was added in https://github.com/markdwags/Razor/commit/b06575992c0caff2155280bc1d3350112928c618
