### ISSUE TITLE
[BUG] appveyor build error...

### ISSUE THREAD

**Issue by andyten** [markdwags/razor#176]
Build started
git clone -q --branch=master https://github.com/andyten/Razor.git C:\projects\razor
git checkout -qf bbe92e8a815a67dffa5b09787052cdd8cfe5c7e1
Patching AssemblyInfo
Patching FastColoredTextBox\Properties\AssemblyInfo.cs...OK
Patching Razor\Properties\AssemblyInfo.cs...OK
nuget restore Razor.sln
MSBuild auto-detection: using msbuild version '16.11.0.36601' from 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin'.
Nothing to do. None of the projects in this solution specify any packages for NuGet to restore.
msbuild "C:\projects\razor\Razor.sln" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
Microsoft (R) Build Engine version 16.11.0+0538acc04 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.
C:\projects\razor\FastColoredTextBox\AutocompleteMenu.cs(43,56): warning CS0109: The member 'AutocompleteMenu.Opening' does not hide an accessible member. The new keyword is not required. [C:\projects\razor\FastColoredTextBox\FastColoredTextBox.csproj]
C:\projects\razor\FastColoredTextBox\AutocompleteMenu.cs(125,27): warning CS0109: The member 'AutocompleteMenu.OnOpening(CancelEventArgs)' does not hide an accessible member. The new keyword is not required. [C:\projects\razor\FastColoredTextBox\FastColoredTextBox.csproj]
C:\projects\razor\FastColoredTextBox\AutocompleteMenu.cs(131,25): warning CS0109: The member 'AutocompleteMenu.Close()' does not hide an accessible member. The new keyword is not required. [C:\projects\razor\FastColoredTextBox\FastColoredTextBox.csproj]
C:\projects\razor\FastColoredTextBox\AutocompleteMenu.cs(164,41): warning CS0109: The member 'AutocompleteMenu.Items' does not hide an accessible member. The new keyword is not required. [C:\projects\razor\FastColoredTextBox\FastColoredTextBox.csproj]
C:\projects\razor\FastColoredTextBox\AutocompleteMenu.cs(190,30): warning CS0109: The member 'AutocompleteMenu.ImageList' does not hide an accessible member. The new keyword is not required. [C:\projects\razor\FastColoredTextBox\FastColoredTextBox.csproj]
  FastColoredTextBox -> C:\projects\razor\bin\Win32\Release\FastColoredTextBox.dll
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2203,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "x86" and the processor architecture of the reference "cuoapi, Version=1.3.0.0, Culture=neutral, processorArchitecture=AMD64", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project. [C:\projects\razor\Razor\Razor.csproj]
C:\projects\razor\Razor\Scripts\Engine\Interpreter.cs(158,18): warning CS0659: 'Variable' overrides Object.Equals(object o) but does not override Object.GetHashCode() [C:\projects\razor\Razor\Razor.csproj]
C:\projects\razor\Razor\UltimaSDK\FileIndex.cs(310,60): warning CS0675: Bitwise-or operator used on a sign-extended operand; consider casting to a smaller unsigned type first [C:\projects\razor\Razor\Razor.csproj]
C:\projects\razor\Razor\Scripts\SpeechCommands.cs(61,25): warning CS0219: The variable 'type' is assigned but its value is never used [C:\projects\razor\Razor\Razor.csproj]
C:\projects\razor\Razor\Core\Targeting.cs(402,29): warning CS0414: The field 'Targeting.m_LTHarmWasSet' is assigned but its value is never used [C:\projects\razor\Razor\Razor.csproj]
C:\projects\razor\Razor\Client\OSI.cs(892,49): warning CS0414: The field 'OSIClient.WM_KEYUP' is assigned but its value is never used [C:\projects\razor\Razor\Razor.csproj]
C:\projects\razor\Razor\Core\Targeting.cs(346,29): warning CS0414: The field 'Targeting.m_LTBeneWasSet' is assigned but its value is never used [C:\projects\razor\Razor\Razor.csproj]
C:\projects\razor\Razor\UI\WelcomeForm.cs(49,22): warning CS0414: The field 'WelcomeForm.m_PatchEncy' is assigned but its value is never used [C:\projects\razor\Razor\Razor.csproj]
CSC : warning CS8012: Referenced assembly 'cuoapi, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null' targets a different processor. [C:\projects\razor\Razor\Razor.csproj]
  Razor -> C:\projects\razor\bin\Win32\Release\Razor.exe
  23 File(s) copied
  stdafx.cpp
  Loader.cpp
     Creating library C:\projects\razor\bin\Win32\Release\Loader.lib and object C:\projects\razor\bin\Win32\Release\Loader.exp
  Loader.vcxproj -> C:\projects\razor\bin\Win32\Release\Loader.dll
  Platform.cpp
     Creating library C:\projects\razor\bin\Win32\Release\Platform.lib and object C:\projects\razor\bin\Win32\Release\Platform.exp
  Platform.vcxproj -> C:\projects\razor\bin\Win32\Release\Platform.dll
  Crypt.cpp
  LoginEncryption.cpp
  MemFinder.cpp
  OldStatusBar.cpp
  OSIEncryption.cpp
  PacketInfo.cpp
  stdafx.cpp
  uo_huffman.cpp
  UOArt.cpp
  Generating Code...
  twofish.c
     Creating library C:\projects\razor\bin\Win32\Release\Crypt.lib and object C:\projects\razor\bin\Win32\Release\Crypt.exp
  Crypt.vcxproj -> C:\projects\razor\bin\Win32\Release\Crypt.dll
SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
python --version
Python 2.7.18
python.exe -m pip install --upgrade pip
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting pip
  Downloading https://files.pythonhosted.org/packages/27/79/8a850fe3496446ff0d584327ae44e7500daf6764ca1a382d2d02789accf7/pip-20.3.4-py2.py3-none-any.whl (1.5MB)
Installing collected packages: pip
  Found existing installation: pip 19.2.3
    Uninstalling pip-19.2.3:
      Successfully uninstalled pip-19.2.3
Successfully installed pip-20.3.4
pip install mkdocs
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting mkdocs
  Downloading mkdocs-1.0.4-py2.py3-none-any.whl (1.2 MB)
Collecting Jinja2>=2.7.1
  Downloading Jinja2-2.11.3-py2.py3-none-any.whl (125 kB)
Collecting livereload>=2.5.1
  Downloading livereload-2.6.3.tar.gz (25 kB)
Collecting tornado>=5.0
  Downloading tornado-5.1.1.tar.gz (516 kB)
Collecting Markdown>=2.3.1
  Downloading Markdown-3.1.1-py2.py3-none-any.whl (87 kB)
Collecting click>=3.3
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting PyYAML>=3.10
  Downloading PyYAML-5.4.1-cp27-cp27m-win32.whl (191 kB)
Collecting MarkupSafe>=0.23
  Downloading MarkupSafe-1.1.1-cp27-cp27m-win32.whl (14 kB)
Requirement already satisfied: six in c:\python27\lib\site-packages (from livereload>=2.5.1->mkdocs) (1.16.0)
Collecting futures
  Downloading futures-3.3.0-py2-none-any.whl (16 kB)
Requirement already satisfied: singledispatch in c:\python27\lib\site-packages (from tornado>=5.0->mkdocs) (3.7.0)
Collecting backports_abc>=0.4
  Downloading backports_abc-0.5-py2.py3-none-any.whl (5.2 kB)
Requirement already satisfied: setuptools>=36 in c:\python27\lib\site-packages (from Markdown>=2.3.1->mkdocs) (41.2.0)
Using legacy 'setup.py install' for livereload, since package 'wheel' is not installed.
Using legacy 'setup.py install' for tornado, since package 'wheel' is not installed.
Installing collected packages: MarkupSafe, Jinja2, futures, backports-abc, tornado, livereload, Markdown, click, PyYAML, mkdocs
    Running setup.py install for tornado: started
    Running setup.py install for tornado: finished with status 'done'
    Running setup.py install for livereload: started
    Running setup.py install for livereload: finished with status 'done'
Successfully installed Jinja2-2.11.3 Markdown-3.1.1 MarkupSafe-1.1.1 PyYAML-5.4.1 backports-abc-0.5 click-7.1.2 futures-3.3.0 livereload-2.6.3 mkdocs-1.0.4 tornado-5.1.1
pip install mkdocs-material
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting mkdocs-material
  Downloading mkdocs_material-7.2.6-py2.py3-none-any.whl (4.2 MB)
ERROR: Could not find a version that satisfies the requirement mkdocs>=1.2.2 (from mkdocs-material) (from versions: 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.10, 0.11, 0.11.1, 0.12.0, 0.12.1, 0.12.2, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.14.0, 0.15.0, 0.15.1, 0.15.2, 0.15.3, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.17.0, 0.17.1, 0.17.2, 0.17.3, 0.17.4, 0.17.5, 1.0a1, 1.0b1, 1.0rc1, 1.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4)
ERROR: No matching distribution found for mkdocs>=1.2.2 (from mkdocs-material)
Command exited with code 1

**Comment by markdwags** [comment]
Sorry, I can't really offer CI support in your own fork. You can remove the mkdocs stuff if you want.
