### ISSUE TITLE
[FEATURE] Resize the Razor Window?

### ISSUE THREAD

**Issue by NewYears1978** [markdwags/razor#178]
I would assume there must be a reason this was never done or at least had been requested before? I always hate when apps force the window size and it makes navigating and using it very difficult. How come the window cannot be resized?

Thanks in advance.

**Is your feature request related to a problem? Please describe.**
Not necessarily a problem just makes using the window difficult since it is a set size and I am on a 1440p monitor. 

**Describe the solution you'd like**
Simply allow the Razor window to be resized instead of a fixed size?

**Describe alternatives you've considered**
Not really any way around this issue.

**Comment by markdwags** [comment]
This is something that I can look at again, but ideally, we just move off of Winforms :)

**Comment by dallenwilson** [comment]
Do you have something in mind to move to? Switching to WPF would drop multi-platform support, while something like GtkSharp would keep multi-platform but mean some extra code to bundle with Razor, much like you've embedded FastColoredTextBox. There are other options beyond those two, as well.

**Comment by markdwags** [comment]
Under this open PR, a lot of great work was put in to isolate the Razor logic with the UI by @sorsarre 

https://github.com/markdwags/Razor/pull/175

I built out a UI a few months back with [AvaloiaUI](http://avaloniaui.net) that I'd use as a base for all the binding to the Razor backend. Here's some pics.

(Windows)
![2021-09-10_16-54-34](https://user-images.githubusercontent.com/577652/143912420-02019f6c-3e90-457b-a171-7ef29dd48c3e.gif)

(Linux)
![2021-09-15_02-47-34](https://user-images.githubusercontent.com/577652/143912437-a9d5f45d-2698-4b38-96ca-60eb2d731a74.gif)

**Comment by markdwags** [comment]
This was added recently

https://github.com/markdwags/Razor/commit/c5ca92e93610c8c33ac98aa845e1545730b3533c
