### ISSUE TITLE
[BUG] Targeting item to add to Restock Agent crashes Razor+ClassicUO on Linux

### ISSUE THREAD

**Issue by canterberry** [markdwags/razor#179]
Client: ClassicUO 0.1.9.31
Razor: v1.7.0.12
Mono: 6.8.0.105
OS: Linux (Ubuntu)
Architecture: x86_64

Something about the "Input Required" dialog when trying to add a targeted item to a Restock Agent crashes Razor.

```
[xcb] Too much data requested fron_XRead
[xcb] This is most likely caused by a broken X extension library
[xcb] Aborting, sorry about that
ClassicUO.bin.x86_64: ../../src/xcb_io.c:741: _XRead: Assertion `!xcb_xlib_too_much_data_requested' failed.
```

In the stack trace is `System.Windows.Forms.Form:ShowDialog` called by `Assistant.InputBox:Show` called by `Assistant.Agents.RestockAgent:OnItemTarget`. The error is ultimately thrown by `System.Windows.Forms.X11Keyboard:XCreateFontSet`.

**Comment by markdwags** [comment]
This PR replaces those input dialogs on agents with an in-game gump now.

https://github.com/markdwags/Razor/commit/511eb3b7e459b1bd02ea53975bb5a19fccc2284e
