### ISSUE TITLE
Client 7x aos status feature not working

### ISSUE THREAD

**Issue by canerksk** [markdwags/razor#185]
Aos status gump does not work on the latest version clients. I think for this, it is necessary to find and add the status addresses of 7x (7.0.91.15) clients. No one has done this on Razor yet. I struggled with it for a while, but gave up halfway.

**Comment by markdwags** [comment]
Closing for now -- if someone wants to work on the old 7.x client to get this going, I'll accept a PR but at this point, ClassicUO is really the focus.
