### ISSUE TITLE
[BUG] findtype backpack hue

### ISSUE THREAD

**Issue by IChris2698I** [markdwags/razor#186]
# Background

I am using ClassicUO. I'm playing on Ruins & Riches. I'm not sure but it may include a modified ClassicUO.exe, though it's packaged with Razor Community Edition 1.7.1.7 (I updated to 1.7.2.25) and most everything else works as expected. I downloaded the game and server/world just a few days ago on 12/17.

# Summary

Using `if findtype '<graphic id>' backpack <hue> as 'found'` finds things on the ground.

# Steps to reproduce

1. I made a script containing the code below. It should find ore in my backpack and move it to the ground. '6585' is the item type for iron ore. 1975 is the hue for Bronze. Regular iron ore is hue 0.
2. I mined a couple iron ore, and a couple bronze ore.
3. I made sure I had 2 different types of ore in my backpack.
4. I ran the script 4 times.
```
if findtype '6585' backpack 1975 as 'found'
    lift 'found' 999
    wait 1000
    droprelloc 0 1
endif
```

# What you expected would happen

1. Bronze ore pile should be moved from my backpack to the ground.
2. Nothing (`if` check should fail)
3. Nothing (`if` check should fail)
4. Nothing (`if` check should fail)

# What actually happens

1. One of the piles of ore is moved from my backpack to the ground.
2. The other pile of ore is moved from my backpack to the ground.
3. One of the piles of ore on the ground is picked up and dropped back on the ground.
4. Same as number 3 above, sometimes with the same pile and sometimes with the other pile.

# Additional notes

`findtype` without a hue works as expected. That is, `if findtype '6585' backpack as 'found'` only finds ore in my backpack, not on the ground.

**Comment by markdwags** [comment]
Please be sure to install version 1.7.3.36 which has this feature -- 1.7.2.25 had it in the release notes but it wasn't in the update. Sorry for the confusion.
