### ISSUE TITLE
[BUG] ClassicUO: "Reload all scripts" does not reload external changes

### ISSUE THREAD

**Issue by gdavis** [markdwags/razor#187]
**Summary**
I am trying to use an external text editor to edit scripts for usage on UO Outlands so I don't have to use the small native window, or the buggy popout editor that consistently crashes and becomes unusable.

I have installed Visual Studio Code to edit files. When saving a change in that editor, or any other external editor, then using the "Reload all scripts" option in the scripts list, the changes in the script are not updated in the client. It will find new files and folders the first time it is reloaded, but if any changes are made to those scripts outside of the Razor client the scripts will not update. The old version is cached in Razor, and running an edited script only uses the previously cached version.

**Steps to reproduce**
1. Open Razor
1. Open an existing .razor script file in Razor
1. Open the same existing script in an external editor outside of Razor
1. Change the script in the external editor and save
1. Right click the scripts list in Razor and select "Reload all scripts"
1. Observe that Razor does not refresh the editor window with the changes made externally.

**Expected Results**
I would expect that Razor not only finds new files and folders when using the "Reload all scripts" action, but also finds changes to files that have been made externally, and refresh the editor window to show these changes. 

I expect a "Reload script" option to check the script file for changes from when it was originally cached, and update the UI with the latest version of the file.

**What actually happened**
Razor shows the version of the script from when it was first displayed in the internal editor. Making a change within Razor to the existing script will overwrite any changes made externally, as the cached version overwrites the file

**Comment by markdwags** [comment]
Do you have any info on `the buggy popout editor that consistently crashes and becomes unusable.` -- any errors or crash logs? I haven't seen any reports of that.

**Comment by gdavis** [comment]
@markdwags I opened a new issue for this crash here: https://github.com/markdwags/Razor/issues/188
