### ISSUE TITLE
[FEATURE] ClassicUO Linux: 'Target Closest Mobile' ignores invulnerable mobiles

### ISSUE THREAD

**Issue by mythril** [markdwags/razor#189]
**Summary**
I was running this script on a Ruins And Riches setup:

```
while not dead
    hotkey 'Target Closest Mobile'
    hotkey 'Last Target'
    menu 'last' 1
    pause 1000
endwhile
````

And I noticed that it never works on invulnerable mobiles, even when they have the menu index in question.

**Steps to reproduce**

1. Open Razor & Client for Ruins & Riches
2. Login
3. Run above script to initiate "Talk" option on nearby mobiles
4. Notice it never selects an invulnerable as the closest mobile (it always chooses the nearest non-invul mobile).

**Expected Results**
Invulnerable mobiles are still counted as mobiles.

**What actually happened**
Invulnerable mobiles are ignored.

**Comment by markdwags** [comment]
This isn't a bug, this is by design and has been this way in Razor at least a decade. Sounds like in your case, you'd like a feature that doesn't exclude blessed (invulnerable) mobiles from the targeting system.

**Comment by mythril** [comment]
Maybe it could be addressed with a new script command / expression that is in a format like:
```
mobile (closest/random/next/previous) (status) (criminal/enemy/friendly/gray/innocent/murderer/non-friendly/combatant/monster/humanoid/blessed) as varname

mobiletype (GraphicID) (hue) (closest/random/next/previous) (status) (criminal/enemy/friendly/gray/innocent/murderer/non-friendly/combatant/blessed) as varname
```

Are there build instructions for this project, I'd like to see what I can contribute, but I run on Linux.

**Comment by mythril** [comment]
I just realized I didn't read the docs for `target` so maybe this is already handled well.

**Comment by mythril** [comment]
I just tried it, there is no option that encompasses the blessed mobiles afaict.

**Comment by markdwags** [comment]
Right, it isn't a feature currently. It would need to be added, to allow you to bypass the blessed check. :)
