### ISSUE TITLE
[Question]: In depth build instructions?

### ISSUE THREAD

**Issue by mythril** [markdwags/razor#190]
I am trying to figure out how I can contribute to the project. I'm running into errors with a simple:

```
msbuild Razor.sln
```
and on Mono
```
xbuild Razor.sln
```

So I was hoping there was a more detailed set of instructions for building Razor somewhere.

Here are a handful of related questions:
What .NET SDK version is it targeting?
Does it build on Linux w/ Mono?
---> How?
Can it be built from the command line?
Do I have to use Visual Studio?

**Comment by dallenwilson** [comment]
I've never been able to get it to build using Mono, but I use Gentoo and the whole mono ecosystem is a bit of a pig's breakfast on that distro, so I count myself lucky I can run Razor at all.

I use Win10 under a VM to build Razor and ClassicUO both, and I use Visual Studio Community Edition to do it. It's free. I've never tried building it from a command line with Windows, so I can't help you there.

I believe the build target is .Net 4.7.2, currently.

As far as detailed build instructions, I just load the .sln and hit 'build solution' and everything Just Works.

I'm not associated with the project in any way, just a user who patches the occasional linux-specific bug when they happen to bite me long enough.

Good luck!
