### ISSUE TITLE
[BUG] Linux & ClassicUO - Razor hangs when user logs out after running a macro

### ISSUE THREAD

**Issue by Phalkon27** [markdwags/razor#196]
I noticed that whenever I run macros or scripts through the appropriate tabs in Razor (not by pressing a hotkey), Razor will hang when I eventually try to log out which forces user to kill it and that prevents Razor from saving any changes made to the profile (hotkeys, settings, etc.).

I'm using Razor build downloaded directly through from this GitHub page with ClassicUO on Linux.

Unfortunately I couldn't find any crash logs from Razor. ClassicUO logs don't show anything out of the ordinary.

**Summary**

Whenever user logs out after running a macro/script through the play button on the Macros or Scripts tab, Razor will hang and won't save any changes made to the profile.

**Steps to reproduce**

    Open ClassicUO with Razor plugin on Linux
    Log in
    Open either Macros or Scripts tab in Razor window
    Run any macro/script by clicking the "Play" button
    Stop macro/script and try to log out

**Expected Results**
After logging out Razor will save changes made to the profile and close.

**What actually happened**
Razor hangs forcing user to kill the process and lose any changes made to the Razor profile.

**Comment by Phalkon27** [comment]
I just discovered, this bug doesn't seem to be present in Razor v1.7.0.12. It looks like it was introduced in v1.7.1.7 and stayed present through all the future updates and is still there in v1.7.4.49 (latest). Hope it helps.

**Comment by Phalkon27** [comment]
Seems to be fixed in [Razor v1.8.61.0](https://github.com/markdwags/Razor/releases/tag/v1.8.61.0)

**Comment by Phalkon27** [comment]
Hmm... I might have spoken too soon. There still seems to be random freezes at logout, I'm just not able to replicate them reliably. [Razor v1.7.0.12](https://github.com/markdwags/Razor/releases/tag/v1.7.0.12) is still working fine though.

**Comment by ghost** [comment]
Experiencing the same bug. Can't seem to isolate it on latest development and stable (v1.9.77.0) releases.
My workaround is just to save my Razor profile before quitting, if I've made significant changes. Since macros and scripts are flat files, they aren't affected.
