### ISSUE TITLE
[BUG] Buy Agent not working properly

### ISSUE THREAD

**Issue by Holy-Cannoli** [markdwags/razor#197]
ClassicUO [dev] 0.1.9.17
Razor v1.7.4.49

**Summary:** When adding items to the Buy Agent within Razor, the list gets completely wiped out upon game restart. 

**Import Issue:**  When trying to import the items from clipboard (!Razor.Agents.Buy), nothing appears to happen. If you import from a profile, it populates the Buy Agent list, but does not work in game even if you have the agent enabled.

**Comment by markdwags** [comment]
Thanks! Fixed in the latest build.
