### ISSUE TITLE
found different issues

### ISSUE THREAD

**Issue by blackwanwinwun** [markdwags/razor#199]
1:
when a script or macro targets a human or a monster, if there is a ghost human or monster closer, it will eat the target instead of being "ignored" as an invalid target. even when a human ghost is not showing, the target still gets lost on the ghost (human or pet)

2: 
yell 'bank' yells indeed (another toon can see it furhter away) but it doesnt generate sysmsg (opening the bank)

3:
>where doesnt work.

**Comment by markdwags** [comment]
Hey, thanks for the reports.

1) If the ghost isn't showing, the client had no idea the mobile exists. I'm trying to replicate this, but all the code that looks at what target to pick, always has a check that the mobile isn't a ghost. I'll keep trying to replicate it.

2) This has been fixed in the latest dev build.

3) I've tried `>where` which is a Razor command, and it works just fine. If the server you play on supports it, `[where` is also working too. Do you have an example where it doesn't work?

**Comment by blackwanwinwun** [comment]
3. this would be on uo renaissance. eventhough ingame >where and even -where (macro) work, in a script it doesnt
![image](https://user-images.githubusercontent.com/117690054/200633277-68b3b332-b1b6-46a6-b9cd-6a4e7ef1ce58.png)

**Comment by markdwags** [comment]
> 3. this would be on uo renaissance. eventhough ingame >where and even -where (macro) work, in a script it doesnt
>    ![image](https://user-images.githubusercontent.com/117690054/200633277-68b3b332-b1b6-46a6-b9cd-6a4e7ef1ce58.png)

`>where` is a command you type, it's not a scripting command.

You might be looking for `say '[where'`

Please review https://www.razorce.com/guide/commands/ for a list of scripting commands that are available.

**Comment by blackwanwinwun** [comment]
> 

of all the tests, that one i didnt do but works perfect.

**Comment by blackwanwinwun** [comment]
1. it seems that when a player or pet dies, the client doesnt automatically change the mobile from "alive" to "dead" if i use spirit speak, the mobile then changes to a true ghost & razor targetting is then properly functional again
2. thank you, i see you added a overhead repeating messages checkbox
3. thank you for your tip.
4. (new) in the latest build, when IDenfitying an item, the system message has disapeared. in the past it was possible to identify a tmap or a weapon for a particular property and use the insysmsg for whatever purpose (sorting) 
5. could razor start a script upon logon? in case of DC, it can resume a skill training or some sort.

**Comment by markdwags** [comment]
4. should be resolved with some message changes, please let me know otherwise.

At the moment, no plan to have script's auto-load at login. Closing issue for now, feel free to reopen if issues still persist.
