### ISSUE TITLE
Get player coordinates

### ISSUE THREAD

**Issue by Zyles** [markdwags/razor#202]
Is it possible to get the current player coordinates?

Or could such a feature be added?

**Comment by mljohnson75** [comment]
[coord
site says [where should do it, but it doesn't. [coord works, though

**Comment by markdwags** [comment]
Commands that start with `[` are usually server commands, not Razor commands. Some servers might have it as `[where`, sounds like in your case its `[coord`.

You can type `>where` to display your current coordinates and use the [if position expression](https://www.razorce.com/guide/expressions/#position) in scripting to do certain things if you are in a certain position. You can also use `if insysmsg` if the server you play on supports those commands.
