### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by markn267** [markdwags/razor#209]
**Client:** Razor v1.0.0.0 with UO Outlands 4.0.0.32 (brand new install as of 1.5 weeks ago)

**Summary:** 
Razor will randomly cease to work (communicate with) UO Outlands. This is happening with Razor-side scripts, macros and hotkeys all failing - they simply do nothing when activated, even after a period of time when they successfully worked. At some random point in time - usually after 5-10 minutes or up to a half hour of gameplay, all macros in-game go unresponsive and do not trigger any in-game action nor message, as if Razor no longer communicates with the game.

**Steps to reproduce:**
Simply running UO Outlands + Razor. It is guaranteed for me that at some point within the first few minutes to the first half hour, Razor ceases to communicate with Outlands and all macros/hotkeys stop working. 
As for scripts, they will 'play' and run for a good 10 minutes until they completely cease, even though the Razor window shows the code block ghosted out with the "stop" button being an option (which is how it looks when it is running properly). With scripts, hitting stop then start will get the script working again.

**Measures taken to troubleshoot:**
-Deleted all scripts, macros and hotkeys from the in-game Macro menu in UO Outlands to eliminate the issue of those macros conflicting with Razor.
-Also deleted all scripts and macros from the Razor profile. Essentially reverted back to vanilla Razor, with no customizations.
-Added outlands.exe to firewall greenlist.
-Turned off VPN (may sound silly but I have gone through every measure to eliminate anything as a possible issue).
-In UO Outlands splash screen, clicked the Gear icon and chose "File Check".
-Log out of account, then in again = issue still exists. Completely close out of Outlands/Razor, then log in again = issue disappears, until it happens once again some time within the next half hour.
-None of the above fixed the issue.

**Example of an issue:**
-This is the most classic and simple issue I have encountered over the past 2 weeks: In Razor under the "Hot Keys" tab >> Items >> Bandage Self = set to Ctrl+B. Hitting Ctrl+B will either bandage the character if injured or display the standard message that the character is not injured. This will work for a time period up to around a half hour until the Ctrl+B keystroke simply does nothing: no response, no message on the lower-left of the in-game screen, etc. 
 
**System used:**
Windows 10 Pro
Intel i7, 3.5GHz, 32 GB RAM, GEforce 780 Ti

**Comment by markdwags** [comment]
I appreciate the level of detail you included. Outlands uses an older fork of this project and has made changes to integrate it into their client. I'd recommend reaching out to them for assistance.
