### ISSUE TITLE
[BUG] Outlands - odd issue with archery script

### ISSUE THREAD

**Issue by WOLFGE1ST** [markdwags/razor#225]
ClassicUO

Basically this script will check if I have a heavy crossbow in hands and switch to crossbow and vise versa. Has worked well for months. Suddenly, after some time playing there is an issue where if I have the crossbow equipped it will not switch to the heavy crossbow. 

I have a version of the script which does the same thing but adds a regular bow into the mix. When I have the regular bow in my backpack it all works fine, except for when switching from crossbow to heavy crossbow. 

I tried changing from the item name type to the number ID type to eliminate potential confusion with the words "crossbow". 

If I haven't played in a while and load up the game it seems to work fine. There is something that happens while playing that seems to bug the script. I've also tried adding the command to clear ignore list to the top just in case the heavy is added to the ignore list somehow, but that wouldn't make sense because like I said it works fine with the version that has the regular bow in the script.

Here is a simplified version of the script that is still having the same issue:

if findtype 'heavy crossbow' lefthand
    if findtype 'crossbow' backpack as 'medium weapon'
        @dclick 'medium weapon'
    endif
elseif findtype 'crossbow' righthand 
            if findtype 'heavy crossbow' backpack as 'heavy weapon'
                @dclick 'heavy weapon'
            endif
elseif findtype 'heavy crossbow' backpack as 'heavy weapon'
                @dclick 'heavy weapon'
endif

**Comment by markdwags** [comment]
You'll have to engage with Outlands support since they use a customized fork off this main project.

If you can replicate this on the main version of Razor, please reopen or support a new issue.
