### ISSUE TITLE
Queue TargetSelf / Queue LastTarget - Seperate Checkbox Options.

### ISSUE THREAD

**Issue by JosephFireborn** [markdwags/Razor#36]
Curious if it is possible to split the option in the menu:

![image](https://user-images.githubusercontent.com/35814425/59855628-52a2be80-9343-11e9-991c-71ebdf8f0c80.png) 

Into two separate options?

**Comment by markdwags** [comment]
It can be split, yes. I'm curious to hear about your use-case on this.

**Comment by JosephFireborn** [comment]
use-case being that my friends who want this feature, want to be able to use queue self to cast gheal/cure/miniheal on themselves as fast as possible, but they do not want to use queue for enemies.

**Comment by markdwags** [comment]
Closing for now. Will revisit.
