### ISSUE TITLE
If Conditional - Cursor Target - Beneficial or Aggressive

### ISSUE THREAD

**Issue by JosephFireborn** [markdwags/Razor#37]
Would like to be able to decide how my targeting will work if I have an aggressive spell or a beneficial spell in my targeting macro. 

For example, if I cast Greater Heal and use my last target macro, in that macro it would check to see if the spell is Beneficial and if so, target the last friend, otherwise, target the last enemy. Basically allowing us to build our own smart targeting system based on our own rules. 

It also allows for better solutions to canceling spells and using the queue system.

**Comment by markdwags** [comment]
Thanks for the idea suggestion, but I don't think I have any plans to implement that type of if conditional. That has the potential to open up advanced targeting macros.

I'll toss the idea of my board so it isn't lost but at the moment, I will close this.
