### ISSUE TITLE
Common target list for macro variables

### ISSUE THREAD

**Issue by dissident76** [markdwags/Razor#39]
Please make one list of targets and various buttons to add them as absolute target, double-click target, lift target, etc. This would make easier to script things like restocking or interacting with mounts and other items that require different types of interactions (targeting, dbl clicking, etc) without having to add them to more than one list

**Comment by markdwags** [comment]
I plugged into the existing macro system and took the path of least resistance when I implemented this feature. I'll take a look and see what's involved with that change.

**Comment by dissident76** [comment]
I'd say it can be done by dropping the DoubleClickVariables class and using only one class for variables.  AbsoluteTargetVariables class seems to contain all the info needed (Attributes in DoubleClickVariables are actually a subset of AbsoluteTargetVariables). It could be renamed to class Variable and used for any type of action later in Actions.cs 

In Actions.cs, classes would stay the same (one class for each type of action), but 
public class DoubleClickVariableAction : MacroAction would use the same list in the foreach loop as the AbsoluteTargetVariableAction (which would be the above mentioned unified Variable class). For instance, the DoubleClickVariableAction would now use "variable.TargetInfo.Serial" instead of "dblclick.Serial" to set the value of its private _serial member.

Not trying to be pushy, I just hope it helps, and that I am not talking nonsense -I only had a quick look at the code and I lost my coding mojo since I quit developing for scuba diving (salt water makes everything rusty, even coding skills :P)
