### ISSUE TITLE
[BUG] Context Menu's Do Not Record

### ISSUE THREAD

**Issue by JosephFireborn** [markdwags/Razor#46]
https://gfycat.com/ThirdPinkArcticwolf

Cannot record context menus in new version of razor. 

Roxya said it was possible to record in old razor and then transfer macro to new one and it works. 

That is all the info I have.

**Comment by aclark13** [comment]
Works on 1.0.14.10 (old razor)
`Assistant.Macros.ContextMenuAction|0x0|2|1060673`

**Comment by markdwags** [comment]
Fixed in https://github.com/markdwags/Razor/commit/8f4f86bf7d0bcf32971c8b5469fc08c582453298
