### ISSUE TITLE
[BUG] Overhead spam when using pets

### ISSUE THREAD

**Issue by BlackTeaOutlands** [markdwags/Razor#48]
Using ClassicUO.

When you attack with pets, and also when a mob dies with pets in your control, it appears that Razor performs an all-names or something similar on the pets as well as the target. You get a spam of text above the pets heads. 

If you disable show incoming creatures/corpses, you will not get the spam of the pets name, but the spam of other messages such as [Last Target] will remain. A workaround is to use the CUO show incoming, and disable it in Razor as well as use filter repeating overhead messages. It works perfectly fine that way, but there are some situation where you don't want to filter overhead messages, and it's also not readily apparent that people will discover this workaround if they encounter it themselves. So all in all, would be better with a fix if it is possible.

Here is how it looks with show incoming enabled in Razor:
https://imgur.com/AIKdElw

Here is how it looks with show incoming disabled in Razor:
https://imgur.com/u7lGcYw

**Comment by markdwags** [comment]
This is a known issue. The workaround has been to disable the CUO show incoming/corpses feature and just use Razor's.

Definitely something that needs to be fixed. I'll leave this issue open until it is.

Thanks for the report.

**Comment by markdwags** [comment]
https://github.com/markdwags/Razor/commit/010d16721693ca275d6e73007ff6c69833452cf5 should have corrected this issue. I added a check to prevent multiple single-clicks being picked up on the same mobile.
