### ISSUE TITLE
[BUG] GumpResponse (Button 6) disconnects client when used in a macro while having a gump open

### ISSUE THREAD

**Issue by BlackTeaOutlands** [markdwags/Razor#50]
Using ClassicUO

Might be Outlands specific.

I made a macro, and the line GumpResponse (Button 6) will disconnect the client with the message Connection lost: SocketError, if the line is executed while any sort of gump is open.

The image below describes it. The button is the one the arrow points to. It doesn't have to be that specific gump open, any will crash it. It doesn't need the other lines in the macro, only the marked line is enough.

![image](https://user-images.githubusercontent.com/39037141/61186163-7e734480-a662-11e9-9db1-08938af7f42e.png)

**Comment by markdwags** [comment]
Appears shard specific, when you send invalid gump responses it can disconnect you.

ie: record gump macro for GumpA, then use that same macro for GumpB without re-recording specifically for that gump.
