### ISSUE TITLE
[BUG]"if counter" throws exception

### ISSUE THREAD

**Issue by dissident76** [markdwags/Razor#56]
Using ClassicUO

When reading macro file from disk, the "if [counter]" statement throws exception. If line deleted and re-added, it will work. Problem does not occur with non-counter objects (i.e. "if Hits > 0" works. "if HealPotion > 0" fails)

If saving macro and then hitting reload macro -without any changes-, it will fail again. Remove line and re-add and it works.

Seems like the "if counter" lines are not read properly from disk, but they are fine if created in memory.

**Comment by markdwags** [comment]
Can you give me an example of a macro causing this? I'm not able to reproduce it.

Though, I did find another bug when trying to test this one regarding an Invalid Cast, so I'll fix that.

**Comment by dissident76** [comment]
Yes, it was saying something about an invalid cast.

This macro throws the exception:
Assistant.Macros.IfAction|50|1|1|wand
Assistant.Macros.EndIfAction


I have a counter for wands, called wand.
