### ISSUE TITLE
[BUG] Remove Weapon before casting

### ISSUE THREAD

**Issue by xG00BERx** [markdwags/Razor#65]
If you have this(Remove weapon before casting) toggled and you go to use a Ninjitsu ability (Death Strike specifically) it will remove the weapon by using this ability...

Not sure why you might have this toggled on a ninja character but it should function like Chivalry where it wont remove abilities when you cast chiv spells.

Thanks.

**Comment by markdwags** [comment]
Fixed by https://github.com/markdwags/Razor/pull/144
