### ISSUE TITLE
[BUG] Razor with classicuo prevents windows (7) from shutting down

### ISSUE THREAD

**Issue by HankTheDrunk** [markdwags/Razor#81]
using ClassicUO, Windows 7

If cuo+razor are running when I tell windows 7 to shutdown razor prevents windows from shutting down even if I tell it to force shut down.  Similar to say if you have an unsaved document windows will prevent shutdown however in that case if you tell it to force shutdown it will close the unsaved document. Razor is somehow keeping windows 7 from shutting down even if told to force close.

**Comment by markdwags** [comment]
Closing help wanted issues -- they can be reopened if someone decides to take it on and has the environment to debug the issue.
