### ISSUE TITLE
[FEATURE] - New Variable - Hidden

### ISSUE THREAD

**Issue by rphilp** [markdwags/Razor#83]
In the new Scripting language, please add the variable 'hidden' that detects if the person is currently hidden. Will help for some backstab and skill gain scripts.

**Comment by markdwags** [comment]
Razor (or the client) isn't aware of mobiles who are hidden. When they hide, the server sends the packet to remove them from the client.  When they are revealed, new mobile packet.

Does this functionality exist in some other assistant?

**Comment by rphilp** [comment]
Its in steam. This is for yourself. I assume there still has to be something.

if not hidden
    useskill 'Hiding'
  else
    useskill 'Stealth'

**Comment by markdwags** [comment]
Ah ok, I get what you're saying now. Thanks for the follow up.
