### ISSUE TITLE
[BUG] Items on ground disappear when dragged

### ISSUE THREAD

**Issue by Slegnor** [markdwags/Razor#85]
OSI client 5.0.9.1 (Patch31) - Razor v1.6.3.42 (doesn't seem to occur with ClassicUO)

- Summary: Items on the ground or added to paperdoll or containers sometimes disappear when dragged.

If the item was on the ground:
1) if you leave the area and return it reappears where it originally was.
2) If you dragged an item to a container or PD, it will be back on the ground at the original location.

If the item was on a PD or in a container when dragged: a re-log is required to make it reappear

- Steps to reproduce (video linked: [Video](https://www.dropbox.com/s/5xnhpmk707xvf8p/2020-03-29-1518-39.mp4?dl=0))
Drag an item onto the ground from PD/container or drag item already on ground.
Item has a high chance to disappear although not 100%.
Leave area and return
Item will be back on ground

Not sure but this looks like the same/similar bug to one in Razor 1.0.14 (https://web.archive.org/web/20131217044352/http://www.runuo.com/community/threads/razor-1-0-14-update-october-2013.535052/)
- Notes: Seems to be a redraw issue in an area around the character?  
If you log in and dont move it usually doesn't occur but after moving it does

**Comment by markdwags** [comment]
Closing help wanted issues -- they can be reopened if someone decides to take it on and still uses the OSI client
