### ISSUE TITLE
[BUG] Crashes when logging in

### ISSUE THREAD

**Issue by comiluv** [markdwags/Razor#88]
Crashes and throws infinite ammount of error windows
Steps to reproduce:
1) Run Razor
2) Type in name and password
3) Select shard
4) Select character
5) Crashes

Crash.log: https://pastebin.com/aMepTAZu

Notes:
Windows 10
Razor version 1.6.4.11
Tested on both OSI client version 7.0.85.15 and ClassicUO version 0.1.3.439
Error window says Packet Filter Exception
This crash seems to happen when there are lots of mobiles doing lots of actions when logging in, like in Ophidians vs Terathans battling each other.

**Comment by markdwags** [comment]
What shard? Also, if you delete (backup) your ClassicUO profile for that character, does it happen when you log in?

**Comment by comiluv** [comment]
It's my shard which I added custom NPCs in Jhelom fighting pit where players can fight free for all style versus lots of NPCs and other players and randomly get an artifact drop. If a player logs in from other area, there's no error message or crash, but if that player logs in from that specific spot, crash log I posted happens.
By deleting ClassicUO profile do you mean files inside RazorFolder/Profiles? or ClassicUOFolder/Data/Profiles?
I couldn't decide which so deleted both and the crash still happens.
The crash also happens when directly running razor.exe and selecting client executable file, without ClassicUO.

edit: to clarify original post, what I meant to say in steps to reproduce was that a player would go through normal log in process and then would crash

**Comment by markdwags** [comment]
Is the shard open to public? If so, what's the info? I'd connect to connect to reproduce since its not happening to me when I try.

**Comment by comiluv** [comment]
I'll quickly open a test center and leave it open for approx. 12 hours

**Comment by comiluv** [comment]
Sent a message to you in discord
