### ISSUE TITLE
[FEATURE] Dark Mode

### ISSUE THREAD

**Issue by Arutosio** [markdwags/Razor#90]

**Comment by markdwags** [comment]
I'd love to do this, and if it wasn't more involved, I would have done this by now.

Unfortunately WinForms don't cater to a dark mode too well without using custom controls (that have cross platform support) which would result in having to replace every single button, list, tab, label, etc with a custom UI element would be a large project.

**Comment by markdwags** [comment]
Due to the technical limitations at the moment, closing for now -- may reevaluate in the future.
