### ISSUE TITLE
[FEATURE] rename razor script exstations

### ISSUE THREAD

**Issue by Arutosio** [markdwags/Razor#92]
I propose to change the name of the extension to
.razors, .script or .rs
There already exist razor files (to avoid confusing)

Is there any intelligence for Visual Studio code to create the script?

**Comment by markdwags** [comment]
Fair point, forgot about Razor in the ASP.NET world. Though .rs is used for Rust .script is a bit generic..

**Comment by markdwags** [comment]
I'd love to built on a VS Code syntax highlighter for Razor Script, feel free to beat me to the finish line on that one. ;)

**Comment by Arutosio** [comment]
> Fair point, forgot about Razor in the ASP.NET world. Though .rs is used for Rust .script is a bit generic..
.rscript
.uors

**Comment by markdwags** [comment]
Decided to stick with .razor at the moment but I'll probably look at `.rscript` in the future if a VS Code syntax highligher is ever created by me or someone else.  Thanks for the suggestion.
