### ISSUE TITLE
[BUG] Unhandled Exception Standard OSI 

### ISSUE THREAD

**Issue by samdoidge** [markdwags/Razor#94]
This is on the Standard OSI client.
Windows 10 Pro connecting to UO Renaissance.

I receive an Unhandled exception box with:

```
System.Net.Sockets.SocketException (0x80004005): The attempted operation is not supported for the type of object referenced
   at System.Net.IPAddress.get_Address()
   at Assistant.ClientCommunication.SetConnectionInfo(IPAddress addr, Int32 port)
   at Assistant.Engine.Main(String[] Args)

```

When Razor loads the client, but the client then loads normally - but I can't create my account - it hangs on 'verifying account'.

**Comment by markdwags** [comment]
Hmm, interesting. Your machine not allowing the application to resolve the DNS entry it seems.

If you use the IP (199.59.161.94) do you have any issues connecting?

**Comment by samdoidge** [comment]
Thanks for the quick response.

I still had the same issue with that IP. Changing my internet connection from a mobile 4G connection to a landline one seems to have resolved it.
