### ISSUE TITLE
[FEATURE] Turn Off update or save existing ClassicUO config

### ISSUE THREAD

**Issue by LukaszChrzanowski** [markdwags/Razor#96]
Fresh install from Your's PowerShell script.

**Problem:**
had to add to ClassicUO.exe.config " <loadFromRemoteSources enabled="true"/>" to load Razor becouse of using newest .NET 4.

Every each open application ClassicUO is checking for updates and then downloads it, then it overrides ClassicUO.exe.config with newest config, deleting any entries there.

Could You set some variable that this didn't occur (update)?

**Comment by markdwags** [comment]
Curious, what changes are you making to that config file?

**Comment by markdwags** [comment]
Closing out due to no response.
