### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by LukaszChrzanowski** [markdwags/Razor#97]
Version "stable".
Installed from script.
Playing on custom UO server.

Symptom: Immediate after death cannot move in any direction. Se only text "I'm dead and I cannot do that"
Restart of game is workaround for now (relogin, without closing application).

**Comment by markdwags** [comment]
What leads you to believe this is a Razor issue?

**Comment by markdwags** [comment]
Closing out due to no response.
