### ISSUE TITLE
[BUG] ClassicUO: Agents

### ISSUE THREAD

**Issue by ObscuredCrow** [markdwags/Razor#98]
**Organizer**
When setup for your backpack and have the target container open, it will not move any item from the container to your backpack. It will work if you have a separate container in your backpack to sort into.

**Restock**
When restocking from a target container to your backpack it will only take items if there is more than one stack. Which stack it takes seems to be random, if there is only one stack it will not restock. This appears to be happening with all containers.

**Scavenger**
Is not picking up items from the ground when enabled, even when right on top of them. I know with the old razor you could set the pick-up range and delay which I didn't see in this one. So I'm assuming it's within 2 tiles similar to the auto-open corpses feature.

_Note: It's possible that I'm performing these incorrectly as I'm basing the functionality on the older version of Razor which could have been changed or settings moved that I didn't notice. If that is the case feel free to direct me in the right direction so I can properly test the functionality and get back to you._

**Comment by markdwags** [comment]
Which version of Razor are you using?

**Comment by ObscuredCrow** [comment]
> Which version of Razor are you using?

v1.6.4.0

**Comment by markdwags** [comment]
Hmm, very odd. I use restock every time I play without that behavior. Most the stuff I'm using it on is a container with a single stack of gold, and other things and it has no problem pulling in 1 or more stacks depending on the amount I set.

Same with scav, works fine for me as well. Scav does have a cache, so it won't keep trying to get items off the ground.  There is a clear scavenger cache hotkey for that.

I'll have to test out that organizer behavior and get back to you.

**Comment by ObscuredCrow** [comment]
I will make a short clip of each so you can see what I mean, maybe I'm doing something wrong so I will go through the setup process as well.

**Comment by ObscuredCrow** [comment]
Here is the link to the video clip I made.
https://youtu.be/xoWjSSJITL0

**Comment by eruspravus** [comment]
> 
> 
> Here is the link to the video clip I made.
> https://youtu.be/xoWjSSJITL0

Yea, it looks like you are using the Organizer Agents wrong. First you are trying to pull gold from a locked down bag using the Organizer, that is not how it works. Organizer only pulls things from your backpack into various containers.

You need to use Restock (that you are using later for bandages, and is working). However if you have one line of bandage in your Restock and 2-3 different piles of bandages in your bag you are restocking from. If you run the Restock multiple times, it will take multiple stacks, as you demonstrate working in the [video around 3:33](https://youtu.be/xoWjSSJITL0?t=213)

Try to look at it this way;
Organizers Agents remove stuff from your character and move them into your house/bank/whatever.
Restock Agents takes stuff from your house/bank/whatever and adds it too your character (but there are limitations if you keep many small stacks around you need to run it multiple times).

Hope this helps.

**Comment by markdwags** [comment]
Thanks for the analysis. Closing this issue based on your response.
