### ISSUE TITLE
[BUG] Profile xml reset most of the variables at opening

### ISSUE THREAD

**Issue by Khayyn00** [markdwags/Razor#99]
Hello,
I'm using ClassicUo with Razor 1.6.4.32.

The issue I'm having is that everytime I restart client, my default profile reset the scriptvariables xml field. 
I checked and when I close the client I have the xml with scriptvariables section like this
`<scriptvariables>`
           `<scriptvariable type="0" flags="0" serial="0x4028374B" x="44" y="65" z="44" gfx="3967" name="test" />`
`</scriptvariables>`

and after opening the client and switch profiles it goes back to 
	`<scriptvariables/>`

edit: I thought it was when I close account, but it actually happens when I switch profiles.

**Comment by Khayyn00** [comment]
![bugDNA](https://user-images.githubusercontent.com/65426647/82163382-16594480-98ab-11ea-812b-2921c3854f5a.PNG)

I forgot, this is the output for one error that it's shown when I switch profile from default to my profile.

**Comment by markdwags** [comment]
If you click Save, before switching profiles, do you still lose it?

**Comment by markdwags** [comment]
No response, closing until response.
